import { themeColors } from '../theme/generate.js';
import { THEME_ROLES, type Theme, type ThemeSet } from '../types.js';

export interface CssVariableOptions {
  /** Prefix for every custom property. Defaults to `hf`. */
  readonly prefix?: string;
  /** Selector for the base theme. Defaults to `:root`. */
  readonly selector?: string;
  /** Selector for the dark theme. Defaults to `[data-theme="dark"]`. */
  readonly darkSelector?: string;
  /** Also emit a `@media (prefers-color-scheme: dark)` block. Defaults to false. */
  readonly prefersColorScheme?: boolean;
  /** Emit the sampled palette as `--<prefix>-sample-1`… Defaults to false. */
  readonly includePalette?: boolean;
  /** Emit `color-scheme` so form controls follow the theme. Defaults to true. */
  readonly includeColorScheme?: boolean;
  /** Indentation unit. Defaults to two spaces. */
  readonly indent?: string;
}

interface ResolvedCssOptions {
  prefix: string;
  selector: string;
  darkSelector: string;
  prefersColorScheme: boolean;
  includePalette: boolean;
  includeColorScheme: boolean;
  indent: string;
}

function resolveOptions(options: CssVariableOptions): ResolvedCssOptions {
  return {
    prefix: options.prefix ?? 'hf',
    selector: options.selector ?? ':root',
    darkSelector: options.darkSelector ?? '[data-theme="dark"]',
    prefersColorScheme: options.prefersColorScheme ?? false,
    includePalette: options.includePalette ?? false,
    includeColorScheme: options.includeColorScheme ?? true,
    indent: options.indent ?? '  ',
  };
}

function variableName(prefix: string, name: string): string {
  return `--${prefix}-${name}`;
}

/**
 * The theme as a flat map of custom properties, for inline styles or for
 * passing straight into a `<style>` tag.
 *
 * ```ts
 * const style = themeToCssVariables(theme); // { '--hf-background': '#f8f4ec', ... }
 * ```
 */
export function themeToCssVariables(
  theme: Theme,
  options: CssVariableOptions = {},
): Record<string, string> {
  const { prefix, includePalette } = resolveOptions(options);
  const colors = themeColors(theme);
  const variables: Record<string, string> = {};

  for (const role of THEME_ROLES) {
    variables[variableName(prefix, role)] = colors[role];
  }
  variables[variableName(prefix, 'on-primary')] = theme.readableInk.onPrimary;
  variables[variableName(prefix, 'on-accent')] = theme.readableInk.onAccent;

  if (includePalette) {
    theme.palette.forEach((sample, index) => {
      variables[variableName(prefix, `sample-${index + 1}`)] = sample.hex;
    });
  }

  return variables;
}

function cssBlock(
  selector: string,
  theme: Theme,
  options: ResolvedCssOptions,
  wrapInMedia = false,
): string {
  const lines = Object.entries(themeToCssVariables(theme, options)).map(
    ([name, value]) => `${options.indent}${name}: ${value};`,
  );
  if (options.includeColorScheme) {
    lines.unshift(`${options.indent}color-scheme: ${theme.mode};`);
  }
  const body = lines.join('\n');
  const block = `${selector} {\n${body}\n}`;
  return wrapInMedia ? `@media (prefers-color-scheme: dark) {\n${indentBlock(block, options.indent)}\n}` : block;
}

function indentBlock(block: string, indent: string): string {
  return block
    .split('\n')
    .map((line) => (line.length > 0 ? `${indent}${line}` : line))
    .join('\n');
}

function paletteComment(theme: Theme): string {
  const samples = theme.palette.map((sample) => sample.hex).join(', ');
  return `/* generated by hueframe from ${theme.palette.length} sampled colours: ${samples} */`;
}

/** One theme as a CSS custom-property block. */
export function exportCssVariables(theme: Theme, options: CssVariableOptions = {}): string {
  const resolved = resolveOptions(options);
  const header = `/* hueframe · ${theme.mode} theme · variation ${theme.variation} */`;
  const palette = resolved.includePalette ? paletteComment(theme) : '';
  return [header, palette, cssBlock(resolved.selector, theme, resolved)]
    .filter((part) => part.length > 0)
    .join('\n');
}

/**
 * Both themes of a set, ready to paste into a stylesheet: a base block plus a
 * dark block (selector, media query, or both).
 */
export function exportThemeSetCss(set: ThemeSet, options: CssVariableOptions = {}): string {
  const resolved = resolveOptions(options);
  const parts = [
    `/* hueframe · light and dark themes from ${set.palette.length} sampled colours */`,
    paletteComment(set.light),
    cssBlock(resolved.selector, set.light, resolved),
    cssBlock(resolved.darkSelector, set.dark, resolved),
  ];

  if (resolved.prefersColorScheme) {
    parts.push(cssBlock(resolved.selector, set.dark, resolved, true));
  }

  return parts.filter((part) => part.length > 0).join('\n\n');
}
