import { describe, expect, it } from 'vitest';

import { extractPalette } from '../extract/extract.js';
import { createThemeSet, generateTheme } from '../theme/generate.js';
import { exportCssVariables, exportThemeSetCss, themeToCssVariables } from './css.js';
import { exportJsonTokens, exportJsonTokensString } from './json.js';

const palette = extractPalette(['#f8f4ec', '#ece5d8', '#213f3b', '#b95d41', '#7c967d']);
const theme = generateTheme(palette);

describe('themeToCssVariables', () => {
  it('maps every role plus the readable inks', () => {
    const variables = themeToCssVariables(theme);
    expect(Object.keys(variables)).toEqual([
      '--hf-background',
      '--hf-surface',
      '--hf-text',
      '--hf-primary',
      '--hf-accent',
      '--hf-on-primary',
      '--hf-on-accent',
    ]);
    expect(variables['--hf-background']).toBe(theme.roles.background.hex);
  });

  it('honours a custom prefix and can include the sampled palette', () => {
    const variables = themeToCssVariables(theme, {
      prefix: 'brand',
      includePalette: true,
    });
    expect(variables['--brand-primary']).toBe(theme.roles.primary.hex);
    expect(variables['--brand-sample-1']).toBe(palette[0].hex);
  });
});

describe('exportCssVariables', () => {
  it('emits a root block with colour-scheme', () => {
    const css = exportCssVariables(theme, { includePalette: true });
    expect(css).toContain(':root {');
    expect(css).toContain('color-scheme: light;');
    expect(css).toContain(`--hf-primary: ${theme.roles.primary.hex};`);
    expect(css).toContain('/* generated by hueframe from 5 sampled colours');
  });

  it('supports a custom selector', () => {
    const css = exportCssVariables(theme, { selector: '.theme-scope' });
    expect(css).toContain('.theme-scope {');
  });
});

describe('exportThemeSetCss', () => {
  it('emits light and dark blocks', () => {
    const set = createThemeSet(palette);
    const css = exportThemeSetCss(set);
    expect(css).toContain(':root {');
    expect(css).toContain('[data-theme="dark"] {');
    expect(css).toContain('color-scheme: dark;');
    expect(css).toContain(set.dark.roles.background.hex);
  });

  it('can add a prefers-color-scheme block', () => {
    const css = exportThemeSetCss(createThemeSet(palette), { prefersColorScheme: true });
    expect(css).toContain('@media (prefers-color-scheme: dark) {');
  });
});

describe('exportJsonTokens', () => {
  it('describes every role as a design token', () => {
    const tokens = exportJsonTokens(theme);
    expect(tokens.mode).toBe('light');
    expect(tokens.color.primary).toEqual({
      $type: 'color',
      $value: theme.roles.primary.hex,
      $description: 'Primary action fill',
    });
    expect(tokens.palette).toHaveLength(5);
    expect(tokens.palette?.[0].$extensions['dev.hueframe'].population).toBeCloseTo(0.2, 4);
    expect(tokens.contrast?.['text-on-background'].aa).toBe(true);
  });

  it('can omit the palette and contrast blocks', () => {
    const tokens = exportJsonTokens(theme, { includePalette: false, includeContrast: false });
    expect(tokens.palette).toBeUndefined();
    expect(tokens.contrast).toBeUndefined();
  });

  it('serialises to parseable JSON', () => {
    const json = exportJsonTokensString(theme);
    expect(json).toContain('\n  ');
    const parsed = JSON.parse(json) as { color: Record<string, { $value: string }> };
    expect(parsed.color.background.$value).toBe(theme.roles.background.hex);
  });

  it('serialises compactly when asked', () => {
    expect(exportJsonTokensString(theme, { pretty: false })).not.toContain('\n');
  });
});
